name: freyja-sra
channels:
    - bioconda
    - conda-forge
dependencies:
  - bioconda::cutadapt=4.4
  - bioconda::freyja=1.5.1
  - bioconda::nextflow=23.04.3
  - bioconda::minimap2=2.26
  - conda-forge::awscli=2.15.25
  - conda-forge::google-cloud-sdk=458.0.1
  - conda-forge::procps-ng=3.3.17
  - hcc::aspera-cli
  - pip:
    - ffq
    - epiweeks